apiVersion: v2
name: k8s-agents-operator
description: A Helm chart for the Kubernetes Agents Operator
type: application
version: '0.16.1'
dependencies:
  - name: common-library
    version: 1.3.0
    repository: "https://helm-charts.newrelic.com"
appVersion: '0.16.1'
home: https://github.com/newrelic-experimental/k8s-agents-operator-windows/blob/main/charts/k8s-agents-operator/README.md
sources:
  - https://github.com/newrelic-experimental/k8s-agents-operator-windows
maintainers:
  - name: csongnr
    url: https://github.com/csongnr
  - name: dbudziwojskiNR
    url: https://github.com/dbudziwojskiNR
  - name: danielstokes
    url: https://github.com/danielstokes
